ren Afghanistan-flag.* AFG.*
ren Aland-islands.* ALA.*
ren Albania-flag.* ALB.*
ren Algeria-flag.* ALG.*
ren American-samoa.* ASA.*
ren Andorra-flag.* AND.*
ren Angola-flag.* ANG.*
ren Anguilla.* AIA.*
ren Antarctica.* ATA.*
ren Antigua-and-barbuda.* ANT.*
ren Argentina-flag.* ARG.*
ren Armenia-flag.* ARM.*
ren Aruba.* ARU.*
ren Australia-flag.* AUS.*
ren Austria-flag.* AUT.*
ren Azerbaijan-flag.* AZE.*
ren Bahamas-flag.* BAH.*
ren Bahrain-flag.* BRN.*
ren Bangladesh-flag.* BAN.*
ren Barbados-flag.* BAR.*
ren Belarus-flag.* BLR.*
ren Belgium-flag.* BEL.*
ren Belize-flag.* BIZ.*
ren Benin-flag.* BEN.*
ren Bermuda.* BER.*
ren Bhutan-flag.* BHU.*
ren Biot.* 
ren Bolivia-flag.* BOL.*
ren Bosnian-flag.* BIH.*
ren Botswana-flag.* BOT.*
ren Bouvet-island.* BVT.*
ren Brazil-flag.* BRA.*
ren British-antarctic-territory.* 
ren British-virgin-islands.* 	IVB.*
ren Brunei-flag.* BRU.*
ren Bulgaria-flag.* BUL.*
ren Burkina-faso-flag.* BUR.*	
ren Burma-flag.* BIR.*
ren Burundi-flag.* BDI.*
ren Cambodia-flag.* CAM.*
ren Cameroon-flag.* CMR.*
ren Canada-flag.* CAN.*
ren Cape-verde-flag.* CPV.*
ren Cascadia.* 
ren Cayman-islands.* CAY.*
ren Centralafricanrepublic*.* CAF.*
ren Chad-flag.* CHA.*
ren Chile-flag.* CHI.*
ren China-flag.* CHN.*
ren Christmas-island.* CXR.*
ren Cocos-islands.* CCK.*
ren Colombia-flag.* COL.*
ren Comoros-flag.* COM.*
ren Congo-flag.* CGO.*
ren Congo-kinshasa.* COD.*
ren Cook-islands.* COK.*
ren Costa-rica-flag.* CRC.*
ren Croatian-flag.* CRO.*
ren Cuba-flag.* CUB.*
ren Cyprus-flag.* CYP.*
ren Czech-republic.* CZE.*
ren Denmark.* DEN.*
ren Djibouti-flag.* DJI.*
ren Dominican-republic-flag.* DOM.*
ren Dominicana.* DMA.*
ren East-timor.* 
ren Ecuador-flag.* ECU.*
ren Egypt-flag.* EGY.*
ren El-salvador-flag.* ESA.*
ren England-flag.* ENG.*
ren Equatorial-guinea-flag.* GEQ.*
ren Eritrea-flag.* ERI.*
ren Estonia.* EST.*
ren Ethiopia-flag.* ETH.*
ren European-union-flag.* EU.*
ren Ex-yugoslavia-flag.* YUG.*
ren Falkland-islands.* FLK.*
ren Faroe-islands.* FRO.*
ren Fiji.* FIJ.*
ren Finland-flag.* FIN.*
ren France-flag.* FRA.*
ren French-polynesia.* PYF.*
ren French-southern-territories.* ATF.*
ren Gabon-flag.* GAB.*
ren Gambia-flag.* GAM.*
ren Georgia-flag.* GEO.*
ren Germany-flag.* GER.*
ren Ghana-flag.* GHA.*
ren Gibraltar-flag.* GIB.*
ren Greece-flag.* GRE.*
ren Greenland-flag.* GRL.*
ren Grenada.* GRN.*
ren Guadeloupe.* GLP.*
ren Guam-flag.* GUM.*
ren Guatemala-flag.* GUA.*
ren Guernsey.* GGY.*
ren Guinea-bissau-flag.* GBS.*
ren Guinea-flag.* GUI.*
ren Guyana-flag.* GUY.*
ren Haiti-flag.* HAI.*
ren Holy-see-flag.* 
ren Honduras-flag.* HON.*
ren Hong-kong-flag.* HKG.*
ren Hungary-flag.* HUN.*
ren Iceland-flag.* ISL.*
ren India-flag.* IND.*
ren Indonesia-flag.* INA.*
ren Iran-flag.* IRI.*
ren Iraq-flag.* IRQ.*
ren Ireland-flag.* IRL.*
ren Isle-of-man-flag.* IMN.*
ren Israel-flag.* ISR.*
ren Italy-flag.* ITA.*
ren Ivory-coast-flag.* CIV.*
ren Jamaica-flag.* JAM.*
ren Jan-mayen-flag.* 
ren Japan-flag.* JPN.*
ren Jarvis-island-flag.* 
ren Jersey-flag.* JEY.*
ren Jordan-flag.* JOR.*
ren Kazakhstan-flag.* KAZ.*
ren Kenya-flag.* KEN.*
ren Kiribati.* KIR.*
ren Korea-flag.* KOR.*
ren Kosovo.* KOS.*
ren Kuwait-flag.* KUW.*
ren Kyrgyzstan-flag.* KGZ.*
ren Laos-flag.* LAO.*
ren Latvia-flag.* LAT.*
ren Lebanon-flag.* LIB.*
ren Lesotho-flag.* LES.*
ren Liberia-flag.* LBR.*
ren Libya-flag.* LBA.*
ren Liechtenstein-flag.* LIE.*
ren Lithuania-flag.* LTU.*
ren Luxembourg-flag.* LUX.*
ren Macau-flag.* MAC.*
ren Macedonia-flag.* MKD.*
ren Madagascar-flag.* MAD.*
ren Malawi-flag.* MAW.*
ren Malaysia.* MAS.*
ren Maldives-flag.* MDV.*
ren Mali-flag.* MLI.*
ren Malta-flag.* MLT.*
ren Marshall-islands-flag.* MHL.*
ren Martinique.* MTQ.*
ren Mauritania-flag.* MTN.*
ren Mauritius-flag.* MRI.*
ren Mayotte-flag.* MYT.*
ren Mexico-flag.* MEX.*
ren Micronesia-flag.* FSM.*
ren Moldova-flag.* MDA.*
ren Monaco-flag.* MON.*
ren Mongolia-flag.* MGL.*
ren Montenegro.* MNE.*
ren Montserrat-flag.* MSR.*
ren Morocco-flag.* MAR.*
ren Mozambique-flag.* MOZ.*
ren Myanmar.* MYA.*
ren Namibia-flag.* NAM.*
ren Nauru-flag.* NRU.*
ren Nepal-flag.* NEP.*
ren Netherlands-antilles.* AHO.*
ren Netherlands-flag.* NED.*
ren New-caledonia-flag.* NCL.*
ren New-zealand.* NZL.*
ren Nicaragua-flag.* NCA.*
ren Niger-flag.* NIG.*
ren Nigeria-flag.* NGR.*
ren Niue-flag.* NIU.*
ren Norfolk-island.* NFK.*
ren North-korea-flag.* PRK.*
ren Northern-ireland.* NIR.*
ren Northern-mariana-islands.* MNP.*
ren Norway-flag.* NOR.*
ren Oman-flag.* OMA.*
ren Pakistan-flag.* PAK.*
ren Palau-flag.* PLW.*
ren Palestinian-territory.* PLE.*
ren Panama-flag.* PAN.*
ren Papua-new-guinea-flag.* PNG.*
ren Paraguay-flag.* PAR.*
ren Peru-flag.* PER.*
ren Philippines-flag.* PHI.*
ren Pitcairn.* PCN.*
ren Poland-flag.* POL.*
ren Portugal-flag.* POR.*
ren Puerto-rico-flag.* PUR.*
ren Qatar-flag.* QAT.*
ren Reunion-flag.png REU.*
ren Romania-flag.* ROU.*
ren Russia-flag.* RUS.*
ren Rwanda-flag.* RWA.*
ren Saint-pierre-and-miquelon.* SPM.*
ren Saint Vincent And The Grenadines*.* VIN.*
ren Saint-barthelemy.* BLM.*
ren Saint-helena-and-dependencies.* SHND.*
ren Saint-helena.* SHN.*
ren Saint-kitts-and-nevis.* SKN.*
ren Saint-lucia-flag.* LCA.*
ren Saint-martin.* MAF.*
ren Saint-pierre-and-miquelon.* 
ren Samoa-flag.* SAM.*
ren San-marino-flag.* SMR.*
ren Sao-tome-and-principe.* STP.*
ren Saudi-arabia-flag.* KSA.*
ren Scotland.* SCO.*
ren Senegal-flag.* SEN.*
ren Serbia-flag.* SRB.*
ren Seychelles-flag.* SEY.*
ren Sierra-leone-flag.* SLE.*
ren Singapore-flag.* SIN.*
ren Sint-eustatius-flag.* 
ren Slovakia-flag.* SVK.*
ren Slovenia-flag.* SLO.*
ren Smom.* 
ren Solomon-islands-flag.* SOL.*
ren Somalia-flag.* SOM.*
ren South-africa-flag.* RSA.*
ren South-georgia.* SGS.*
ren South-sudan-flag.* 
ren Spain-flag.* ESP.*
ren Spm.* 
ren Sri-lanka-flag.* SRI.*
ren Sudan-flag.* SUD.*
ren Suriname-flag.* SUR.*
ren Svalbard-flag.* SJM.*
ren Svg.* 
ren Swaziland-flag.* SWZ.*
ren Sweden-flag.* SWE.*
ren Switzerland-flag.* SUI.*
ren Syria-flag.* SYR.*
ren Taiwan-flag.* TPE.*
ren Tajikistan-flag.* TJK.*
ren Tanzania-flag.* TAN.*
ren Thailand-flag.* THA.*
ren Timor-leste-flag.* TLS.*
ren Togo-flag.* TOG.*
ren Tokelau.* TKL.*
ren Tonga-flag.* TGA.*
ren Trinidad-and-tobago.* TRI.*
ren Tunisia-flag.* TUN.*
ren Turkey-flag.* TUR.*
ren Turkmenistan-flag.* TKM.*
ren Turks-and-caicos-islands.* TCA.*
ren Tuvalu.* TUV.*
ren Uganda-flag.* UGA.*
ren Ukraine-flag.* UKR.*
ren United-arab-emirates.* UAE.*
ren United-kingdom-flag.* GBR.*
ren United-states-flag.* USA.*
ren Uruguay-flag.* URU.*
ren Uzbekistan-flag.* UZB.*
ren Vanuatu-flag.* VAN.*
ren Vatican-city.* VAT.*
ren Venezuela-flag.* VEN.*
ren Vietnam-flag.* VIE.*
ren Virgin-islands-flag.* ISV.*
ren Wales.* WAL.*
ren Wallis-and-futuna-flag.* WLF.*
ren Western-sahara.* ESH.*
ren Yemen-flag.* YEM.*
ren Zambia-flag.* ZAM.*
ren Zimbabwe-flag.* ZIM.*